# https://circleci.com/docs/2.0/language-javascript/

version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v2-dependencies-{{ .Branch }}-
            - v2-dependencies-
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}

      - run: yarn run lint
      - run: yarn run test-ci
      - run:
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
            ./cc-test-reporter format-coverage -t lcov -o coverage/codeclimate.json test/coverage/lcov.info
            ./cc-test-reporter upload-coverage || true

      - store_artifacts:
          path: test/coverage
          destination: coverage
