name: publish
on:
  push:
    branches: [master]
    tags: [v*.*.*]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - run: npm install --global pnpm
      - run: pnpm install --frozen-lockfile
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
      - run: pnpm run build
      - run: bun run lint
      - run: bun run test
      - run: cd dist && zip ../chrome-extension.zip *
      - uses: maxmilton/action-create-release@v0
        with:
          files: |
            chrome-extension.zip
          git-tag: ${{ github.ref }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
